---
title: "2015 Pronouns"
author: "Robin Sifre"
date: "6/10/2021"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "../")

library(tidyverse)
library(lubridate)
library(DT)
library(knitr)
```

```{r}
# Loads data 
source('01_setup_import.R')
```

# About
The questions from 2015 Pronouns are different enough that they are exported separately as their own items.
```{r}
s15 <- s15_gnc %>%
  select(child_id, subjectid, Transition,
         # Has your child had a formal "Social Transition"? 1=Yes, 2=No, 3=In the process 
         strans_15 = Transition,
         # At what age did your child's formal social transition occur?  
         strans_age_15 = TransAge,
         # Was your child's social transition phased? (1=No, 2=Yes)
         strans_phased_15 = TransPhase, 
         # You answered on the previous page that your child's social transition was phased. Please briefly explain/clarify the progression of this transition. 
         strans_phased_TEXT_15 = ExplnPhase, 
         # SugstTrans Who first suggested your child's Social Transition?
         strans_suggest_15 = SugstTrans,
         strans_suggest_TEXT_15 = SugstTrans_5_TEXT,
         # TransBeh Does your child do any of the following?  Use pronoun opther than corresponding to bio sex? 
         # use first name other than bio/sex? Wear clothing other than bio/sex? 
         strans_bx_15 = TransBeh,
         # Age that child started using pronoun that does not correspond to biological/anatomical sex 
         pron_age_15 = PronounAg, 
         # Who suggested this?
         pron_suggest_15 = PronounSuggest,
         # Age they use other pronouns 
         age_school_15 = PronContex_School,
         age_home_15 = PronContex_Home,
         age_extfam_15 = PronContex_ExtFam,
         age_bffs_15 = PronContex_BestFriends,
         age_dist_friends_15 = PronContex_DistFriends,
         age_public_15 = PronContex_Public,
         age_name_diff_15 = NameAge,
         age_clothes_diff_15 = ClothesAge,
         # Name
         name_age_15 = NameAge,
         name_suggest_15 = NameSuggest,
         clothes_age_15 = ClothesAge,
         clothes_suggest_15 = ClothesSuggest,
         # 1=boy, 2=girl, 3=other (can only select one)
         pro_school_15 = Schoo,
         pro_home_15 = Home,
         pro_extfam_15 = ExtFam,
         pro_bffs_15 = BestFriends,
         pro_dist_friends_15 = DistFriends,
         pro_public_15 = Public,
         stran_before_15 = BeforeTran,
         stran_after_15 = AfterTran) %>%
  # age_name_diff & age_clothes_diff need to be re-coded
  mutate(age_name_diff = age_name_diff/2,
         age_clothes_diff = age_clothes_diff/2) %>%
   # Note - Qualtrics codes NA at 99. There are 2 cases with NAs with age_school, but they did answer the other items. So ok to assume that they saw and skipped this context bc it does not apply? 
  mutate(age_school = ifelse(age_school==99, NA, age_school),
         age_home = ifelse(age_home==99, NA, age_home),
         age_ext_fam = ifelse(age_ext_fam==99, NA, age_ext_fam),
         age_bffs = ifelse(age_bffs==99, NA, age_bffs),
         age_dist_friends = ifelse(age_dist_friends==99, NA, age_dist_friends),
         age_public = ifelse(age_public==99, NA, age_public))
```

